const D=window.GALLERY_DATA;let query="",cat="All",shown=24,saved=JSON.parse(localStorage.getItem("adilSaved")||"[]"),current=null;
const grid=document.querySelector("#grid"), result=document.querySelector("#result"), search=document.querySelector("#search"), modal=document.querySelector("#modal");
function matches(x){let s=(x.title+" "+x.category+" "+x.tags).toLowerCase();return (!query||s.includes(query.toLowerCase()))&&(cat==="All"||x.category===cat)}
function render(){let list=D.filter(matches);result.textContent=`${list.length} ${list.length===1?"photo":"photos"}`;grid.innerHTML=list.slice(0,shown).map(x=>`<article class="card" data-id="${x.id}"><button class="heart ${saved.includes(x.id)?"active":""}" data-save="${x.id}">${saved.includes(x.id)?"♥":"♡"}</button><img loading="lazy" src="${x.src}" alt="${x.title}"><div class="overlay"><h3>${x.title}</h3><small>${x.category}</small></div></article>`).join("");document.querySelector("#load").style.display=list.length>shown?"block":"none";document.querySelectorAll(".card").forEach(c=>c.onclick=e=>{if(e.target.closest(".heart"))return;openModal(+c.dataset.id)});document.querySelectorAll("[data-save]").forEach(b=>b.onclick=e=>{e.stopPropagation();toggleSave(+b.dataset.save)});document.querySelector("#savedCount").textContent=saved.length}
function toggleSave(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];localStorage.setItem("adilSaved",JSON.stringify(saved));render();if(current?.id===id)updateModal()}
function openModal(id){current=D.find(x=>x.id===id);updateModal();modal.classList.add("open");document.body.style.overflow="hidden"}
function updateModal(){document.querySelector("#modalImg").src=current.src;document.querySelector("#modalTitle").textContent=current.title;document.querySelector("#modalCat").textContent=current.category;document.querySelector("#save").textContent=saved.includes(current.id)?"♥ Saved":"♡ Save"}
document.querySelector("#close").onclick=()=>{modal.classList.remove("open");document.body.style.overflow=""};modal.onclick=e=>{if(e.target.classList.contains("modal-bg"))document.querySelector("#close").click()}
document.querySelector("#save").onclick=()=>toggleSave(current.id);
document.querySelector("#download").onclick=()=>{const a=document.createElement("a");a.href=current.src;a.download=current.title.replace(/\s+/g,"-").toLowerCase()+".jpg";a.target="_blank";a.click()}
search.oninput=()=>{query=search.value.trim();shown=24;render()};document.querySelector("#clear").onclick=()=>{search.value="";query="";render()};document.querySelector("#load").onclick=()=>{shown+=24;render()}
document.querySelectorAll(".catbar [data-cat]").forEach(b=>b.onclick=()=>{cat=b.dataset.cat;document.querySelectorAll(".catbar button").forEach(x=>x.classList.remove("active"));b.classList.add("active");shown=24;render();document.querySelector("#gallery").scrollIntoView({behavior:"smooth",block:"start"})});
document.querySelectorAll("#quick button").forEach(b=>b.onclick=()=>{search.value=b.dataset.q;query=b.dataset.q;shown=24;render();document.querySelector("#gallery").scrollIntoView({behavior:"smooth"})});
document.querySelector("#savedBtn").onclick=()=>{query="";search.value="";cat="All";document.querySelectorAll(".catbar button").forEach(x=>x.classList.toggle("active",x.dataset.cat==="All"));const old=D.filter(x=>saved.includes(x.id));grid.innerHTML=old.map(x=>`<article class="card" data-id="${x.id}"><button class="heart active" data-save="${x.id}">♥</button><img loading="lazy" src="${x.src}" alt="${x.title}"><div class="overlay"><h3>${x.title}</h3><small>${x.category}</small></div></article>`).join("");result.textContent=`${old.length} saved photos`;document.querySelector("#load").style.display="none";document.querySelector("#gallery").scrollIntoView({behavior:"smooth"})}
document.addEventListener("keydown",e=>{if(e.key==="Escape"&&modal.classList.contains("open"))document.querySelector("#close").click()});render();